# Generated by Django 5.0.4 on 2025-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
