# Generated by Django 5.0.4 on 2025-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='tag',
            field=models.CharField(choices=[('all', 'All'), ('meeting', 'Meeting'), ('event', 'Event'), ('economic', 'Economic'), ('education', 'Education')], default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='tags',
            field=models.CharField(choices=[('loksewa', 'Loksewa'), ('training', 'Training')], default='loksewa', max_length=100),
        ),
        migrations.AlterField(
            model_name='welcomecontent',
            name='tag',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='secondary', max_length=100),
        ),
    ]
