# Generated by Django 5.0.4 on 2025-05-08 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0004_alter_event_category_alter_gallerypost_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypost',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery_thumbnails/'),
            preserve_default=False,
        ),
    ]
