# Generated by Django 5.0.4 on 2025-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0005_gallerypost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='False'),
        ),
    ]
