# Generated by Django 5.0.4 on 2025-05-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0006_alter_event_is_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
