# Generated by Django 5.0.4 on 2025-05-11 06:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0008_videopost'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='issues/')),
                ('issue_type', models.CharField(choices=[('climate', 'Climate Change'), ('immigration', 'Comprehensive Immigration Reform'), ('economic', 'Economic Opportunity'), ('health', 'Health Care')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
