# Generated by Django 5.0.4 on 2025-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0009_issueplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Member Events', 'Member Events'), ('Employee Engagement', 'Employee Engagement'), ('Professional Development', 'Professional Development'), ('Industry-Specific', 'Industry-Specific'), ('Techonology', 'Techonology'), ('Awareness', 'Awareness')], default='offline', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='tag',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('event', 'Event')], default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='issueplan',
            name='issue_type',
            field=models.CharField(choices=[('HR Related', 'HR Related'), ('Operation Related', 'Operation Related'), ('Credit Related', 'Credit Related'), ('IT Related', 'IT Related')], max_length=50),
        ),
    ]
