# Generated by Django 5.0.4 on 2025-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0010_alter_event_category_alter_gallerypost_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('url', models.URLField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
