# Generated by Django 5.0.4 on 2026-02-05 09:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0011_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('document_link', models.FileField(upload_to='elibrary_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
