# Generated by Django 5.0.4 on 2026-02-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0012_elibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elibrary',
            name='description',
        ),
    ]
