# Generated by Django 5.0.4 on 2026-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0013_remove_elibrary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrary',
            name='document_link',
            field=models.FileField(max_length=500, upload_to='elibrary_documents/'),
        ),
    ]
